INSERT INTO APP.PNSM_INSTRUCTOR_PNSM_COURSES (INSTRUCTORLIST_INSTRUCTOR_ID, COURSELIST_COURSE_ID) 
	VALUES ('e666', 1);
INSERT INTO APP.PNSM_INSTRUCTOR_PNSM_COURSES (INSTRUCTOR_INSTRUCTOR_ID, COURSELIST_COURSE_ID) 
	VALUES ('e666', 2);
INSERT INTO APP.PNSM_INSTRUCTOR_PNSM_COURSES (INSTRUCTOR_INSTRUCTOR_ID, COURSELIST_COURSE_ID) 
	VALUES ('e666666', 3);
INSERT INTO APP.PNSM_INSTRUCTOR_PNSM_COURSES (INSTRUCTOR_INSTRUCTOR_ID, COURSELIST_COURSE_ID) 
	VALUES ('e666666', 4);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7432263', 1);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7432263', 2);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7432263', 3);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7432263', 4);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7308120', 1);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7308120', 3);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7308120', 4);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7183102', 1);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7183102', 2);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('7183102', 3);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('666666', 3);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('6583832', 1);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('6583832', 2);
INSERT INTO APP.PNSM_STUDENTS_PNSM_COURSES (STUDENTLIST_STUDENT_ID, COURSELIST_COURSE_ID) 
	VALUES ('6583832', 3);